import type { FileKind, OfficeFile, SlideData } from '../types';

export const uid = () => crypto.randomUUID();
const now = Date.now();
function file(id:string, name:string, kind:FileKind, content:any, age:number, starred=false):OfficeFile { return {id,name,kind,content,updatedAt:now-age,createdAt:now-age,starred,trashed:false}; }
export const welcomeDocument = `<h1>A little space for big ideas.</h1><p>Welcome to Folio, your personal workspace for the things you want to create.</p><p>Every great project starts somewhere. A few thoughts on a page. A plan coming together. An idea worth sharing. This is your space to make it happen.</p><h2>Make yourself at home</h2><ul><li><strong>Write freely.</strong> Create documents with headings, lists, tables, and your own style.</li><li><strong>Find the story in your numbers.</strong> Build spreadsheets with formulas and clear, simple data.</li><li><strong>Bring an idea to life.</strong> Create a presentation, one beautiful slide at a time.</li></ul><h2>Your work, in your hands</h2><p>Your files are saved in this browser on this device. Download a copy whenever you need it, in familiar Word, Excel, and PowerPoint formats.</p><blockquote><p>“The secret of getting ahead is getting started.”</p></blockquote><p>Ready when you are.</p>`;
export const makeSlides = (title='Your next big idea'):SlideData[] => [{id:uid(),title,subtitle:'A little inspiration. A fresh perspective.',body:'Created with Folio',background:'#e8eee5',layout:'title'},{id:uid(),title:'Start with a simple idea',body:'What do you want to change?\nWhy does it matter?\nWhat will you do next?',background:'#ffffff',layout:'content'},{id:uid(),title:'Let’s make it happen.',body:'Big things begin with small steps.',background:'#203e35',layout:'title'}];
export const budgetCells = {A1:'Monthly budget',A3:'Category',B3:'Planned',C3:'Actual',D3:'Remaining',A4:'Marketing',B4:'2500',C4:'2150',D4:'=B4-C4',A5:'Software',B5:'800',C5:'690',D5:'=B5-C5',A6:'Operations',B6:'3200',C6:'3050',D6:'=B6-C6',A7:'Team events',B7:'1000',C7:'750',D7:'=B7-C7',A8:'Total',B8:'=SUM(B4:B7)',C8:'=SUM(C4:C7)',D8:'=SUM(D4:D7)'};
export const initialFiles:OfficeFile[] = [
file('welcome','Getting started with Folio','document',welcomeDocument,1000*60*12,true),
file('proposal','Website redesign proposal','document','<h1>Website redesign proposal</h1><p><strong>Prepared for:</strong> The Studio Team</p><h2>Overview</h2><p>A thoughtful refresh of our digital home, built around the people who use it. This proposal outlines the goals, approach, and timeline for our next chapter.</p><h2>Our goals</h2><ul><li>Make our work easier to discover.</li><li>Create a consistent and accessible experience.</li><li>Tell a clearer story about who we are.</li></ul><h2>Project timeline</h2><p><strong>Phase 1 — Discover:</strong> Research, stakeholder interviews, and content audit.</p><p><strong>Phase 2 — Design:</strong> Visual direction, wireframes, and prototyping.</p><p><strong>Phase 3 — Deliver:</strong> Development, testing, and launch.</p>',1000*60*60*2,true),
file('budget','Q3 marketing budget','spreadsheet',{name:'Budget',cells:budgetCells},1000*60*60*5),
file('presentation','Brand strategy presentation','presentation',makeSlides('A brand built for what’s next.'),1000*60*60*24,true),
file('meeting','Weekly team notes','document','<h1>Weekly team notes</h1><p>Good ideas start with a conversation.</p><h2>This week’s focus</h2><ul><li>Review the website proposal and agree on next steps.</li><li>Finalize our quarterly marketing budget.</li><li>Share progress on the new brand direction.</li></ul><h2>Action items</h2><p>Capture the next steps and give each one an owner.</p><h2>Notes</h2><p>Start writing here…</p>',1000*60*60*24*2),
];
export interface Template {id:string;name:string;description:string;kind:FileKind;category:string;content:any;style:string;}
export const templates:Template[] = [
{id:'project',name:'Project proposal',description:'Turn a great idea into a clear plan.',kind:'document',category:'Planning',style:'proposal',content:'<p>PROJECT PROPOSAL</p><h1>A thoughtful plan.<br>A meaningful impact.</h1><p>Prepared by your team · October 2026</p><h2>01 / The opportunity</h2><p>Describe the challenge you want to solve and the opportunity ahead.</p><h2>02 / Our approach</h2><p>Outline how you will bring this project to life.</p><h2>03 / What success looks like</h2><p>Define your goals, deliverables, and how you will measure progress.</p><h2>04 / Timeline & next steps</h2><p>Add your key milestones and next actions.</p>'},
{id:'planner',name:'Monthly budget',description:'A little clarity for every dollar.',kind:'spreadsheet',category:'Personal',style:'budget',content:{name:'Monthly budget',cells:budgetCells}},
{id:'pitch',name:'Pitch deck',description:'Give your next big idea a stage.',kind:'presentation',category:'Business',style:'pitch',content:makeSlides('Good ideas deserve a great story.')},
{id:'resume',name:'Simple résumé',description:'Make a memorable first impression.',kind:'document',category:'Personal',style:'resume',content:'<h1>Your name</h1><p>Your role · your@email.com · Your city</p><h2>Profile</h2><p>A short introduction to who you are and the value you bring.</p><h2>Experience</h2><p><strong>Role title — Company name</strong></p><p>2024 – Present</p><ul><li>Your most meaningful achievement.</li><li>The impact you made on your team or customers.</li></ul><h2>Education</h2><p><strong>Degree — University</strong></p><p>Year of graduation</p><h2>Skills</h2><p>Your core skills and areas of expertise.</p>'},
{id:'tracker',name:'Project tracker',description:'Keep the little details on track.',kind:'spreadsheet',category:'Planning',style:'tracker',content:{name:'Project tracker',cells:{A1:'Project tracker',A3:'Task',B3:'Owner',C3:'Status',D3:'Due date',A4:'Kickoff meeting',B4:'You',C4:'Complete',D4:'Oct 5',A5:'Research',B5:'You',C5:'In progress',D5:'Oct 9',A6:'First draft',B6:'You',C6:'Not started',D6:'Oct 15'}}},
{id:'report',name:'Quarterly review',description:'Celebrate progress. Plan what’s next.',kind:'presentation',category:'Business',style:'report',content:makeSlides('A quarter of moving forward.')},
];
export function blankContent(kind:FileKind) {return kind==='document'?'<p></p>':kind==='spreadsheet'?{name:'Sheet 1',cells:{}}:[{id:uid(),title:'Untitled presentation',subtitle:'Your story starts here.',body:'',background:'#e8eee5',layout:'title'}];}
