import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import JSZip from 'jszip';
const browser = await chromium.launch({ headless: true, executablePath: '/usr/bin/chromium', args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1500, height: 1000 } });
const errors = []; page.on('pageerror', error => errors.push(error.message));
const name = 'Document tools test';
await page.goto(process.env.BASE_URL || 'http://localhost:5173');
await page.locator('.file-name').first().waitFor();
await page.waitForLoadState('networkidle');
await page.getByRole('button', { name: 'New document', exact: false }).click();
await expect(page.locator('.tiptap')).toBeVisible();
await page.getByLabel('Document name').fill(name);
await page.getByLabel('Document name').press('Enter');
await page.locator('.tiptap').evaluate(node => node.editor.commands.setContent('<p>alpha <strong>beta</strong> alpha alphabet Alpha.</p><p>second paragraph</p>'));
const select = async text => page.evaluate(text => {
  const editor = document.querySelector('.tiptap').editor;
  let range;
  editor.state.doc.descendants((node, pos) => { if (!range && node.isText && node.text.includes(text)) range = { from: pos + node.text.indexOf(text), to: pos + node.text.indexOf(text) + text.length }; });
  if (!range) throw new Error(`No text: ${text}`);
  editor.chain().focus().setTextSelection(range).run();
}, text);
const html = () => page.locator('.tiptap').evaluate(node => node.editor.getHTML());
try {
  await select('beta');
  await page.getByRole('button', { name: 'Superscript', exact: true }).click();
  assert.match(await html(), /<sup>beta<\/sup>/);
  await page.getByRole('button', { name: 'Subscript', exact: true }).click();
  assert.match(await html(), /<sub>beta<\/sub>/); assert.doesNotMatch(await html(), /<sup>/);
  await page.getByRole('button', { name: 'Copy formatting', exact: true }).click();
  await select('second');
  await page.getByRole('button', { name: 'Apply formatting', exact: true }).click();
  assert.match(await html(), /<strong><sub>second<\/sub><\/strong>/);
  await page.getByRole('button', { name: 'Increase indent', exact: true }).click();
  assert.match(await html(), /data-indent="1"/);
  await select('paragraph'); await page.getByLabel('Change case').selectOption('upper');
  assert.match(await html(), /PARAGRAPH/);
  await page.getByRole('button', { name: 'Find in document' }).click();
  await page.getByLabel('Find text', { exact: true }).fill('alpha beta');
  await expect(page.locator('.doc-find-panel small')).toHaveText('1 matches');
  await page.getByLabel('Find text', { exact: true }).fill('alpha');
  await page.getByLabel('Match case').check(); await page.getByLabel('Whole word').check();
  await expect(page.locator('.doc-find-panel small')).toHaveText('2 matches');
  await page.getByLabel('Replace text', { exact: true }).fill('omega');
  await page.getByRole('button', { name: 'Find next', exact: true }).click();
  await page.getByRole('button', { name: 'Replace', exact: true }).click();
  assert.match(await html(), /omega/); assert.match(await html(), /alphabet Alpha/);
  await page.getByRole('button', { name: 'Replace all', exact: true }).click();
  await expect(page.locator('.doc-find-panel small')).toHaveText('0 matches');
  await page.getByRole('button', { name: 'Close find and replace' }).click();
  await page.getByRole('button', { name: 'Review', exact: true }).click();
  await select('PARAGRAPH');
  await page.getByRole('button', { name: 'New comment', exact: true }).click();
  await page.getByLabel('Comment text').fill('Please verify this paragraph.');
  await page.getByRole('button', { name: 'Add comment', exact: true }).click();
  await expect(page.locator('.doc-comment-card')).toContainText('Please verify');
  assert.match(await html(), /data-comment-id="[^"]+"[^>]*>PARAGRAPH/);
  await page.getByRole('button', { name: 'Resolve', exact: true }).click();
  await expect(page.locator('.doc-comment-card')).toHaveCount(0);
  await page.getByLabel('Show resolved').check();
  await expect(page.locator('.doc-comment-card')).toHaveClass(/is-resolved/);
  await page.getByRole('button', { name: 'Reopen', exact: true }).click();
  await page.getByTitle('Switch to reading').click();
  await expect(page.getByRole('button', { name: 'Resolve', exact: true })).toBeDisabled();
  await expect(page.getByRole('button', { name: 'Delete comment', exact: true })).toBeDisabled();
  await expect(page.locator('.tiptap')).toHaveAttribute('contenteditable', 'false');
  await page.getByTitle('Switch to editing').click();
  await page.getByRole('button', { name: 'Close comments' }).click();
  await page.getByRole('button', { name: 'Layout', exact: true }).click();
  await page.getByLabel('Paper size').selectOption('legal');
  await page.getByLabel('Page orientation').selectOption('landscape');
  await page.getByLabel('Page margins').selectOption('narrow');
  await page.getByRole('button', { name: 'Header & footer', exact: true }).click();
  await page.getByLabel('Header text').fill('Folio test header');
  await page.getByLabel('Footer text').fill('Folio test footer');
  await page.getByLabel('Include page numbers').check();
  await page.getByRole('button', { name: 'Apply', exact: true }).click();
  await expect(page.locator('.doc-page-header')).toHaveText('Folio test header');
  await page.getByRole('button', { name: 'Insert', exact: true }).click();
  await page.locator('.tiptap').evaluate(node => node.editor.commands.setTextSelection(node.editor.state.doc.content.size - 1));
  await page.getByRole('button', { name: 'Page break', exact: true }).click();
  await expect(page.locator('.tiptap [data-page-break]')).toHaveCount(1);
  await page.getByRole('button', { name: 'Table', exact: true }).click();
  await page.getByRole('button', { name: 'Insert table', exact: true }).click();
  await page.locator('.tiptap').evaluate(node => { const positions = []; node.editor.state.doc.descendants((n, pos) => { if (n.type.name === 'tableHeader') positions.push(pos); }); node.editor.commands.setCellSelection({ anchorCell: positions[0], headCell: positions[1] }); });
  await expect(page.getByRole('button', { name: 'Merge cells', exact: true })).toBeEnabled();
  await page.getByRole('button', { name: 'Merge cells', exact: true }).click();
  await expect(page.locator('.tiptap th[colspan="2"]')).toHaveCount(1);
  await page.getByLabel('Cell background').fill('#abcdef');
  await expect(page.locator('.tiptap th[colspan="2"]')).toHaveCSS('background-color', 'rgb(171, 205, 239)');
  await page.getByRole('button', { name: 'Split cell', exact: true }).click();
  await expect(page.locator('.tiptap th[colspan="2"]')).toHaveCount(0);
  await page.getByRole('button', { name: 'Toggle header row', exact: true }).click();
  await expect(page.locator('.tiptap th')).toHaveCount(0);
  await page.locator('.tiptap').evaluate(node => { const editor = node.editor; editor.commands.insertContentAt(editor.state.doc.content.size, { type: 'image', attrs: { src: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==', alt: 'Test image' } }); let position; editor.state.doc.descendants((n, pos) => { if (n.type.name === 'image') position = pos; }); editor.commands.setNodeSelection(position); });
  await page.getByLabel('Image width', { exact: true }).fill('');
  await page.getByLabel('Image width', { exact: true }).pressSequentially('240');
  await expect(page.getByLabel('Image width', { exact: true })).toBeFocused();
  await page.getByLabel('Image width', { exact: true }).press('Enter');
  await page.getByRole('button', { name: 'Image align right', exact: true }).click();
  await expect(page.locator('.tiptap img')).toHaveAttribute('width', '240');
  await expect(page.locator('.tiptap img')).toHaveAttribute('data-align', 'right');
  await page.getByRole('button', { name: 'Review', exact: true }).click();
  await page.getByRole('button', { name: 'Version history', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Version history' })).toBeVisible();
  await page.getByRole('button', { name: 'Close version history' }).click();
  await page.getByRole('button', { name: 'Back to workspace', exact: true }).click();
  await page.reload();
  await page.locator('.file-name').filter({ hasText: name }).click();
  await expect(page.locator('.tiptap [data-page-break]')).toHaveCount(1);
  await expect(page.locator('.tiptap img')).toHaveAttribute('width', '240');
  await expect(page.locator('.doc-page-header')).toHaveText('Folio test header');
  await page.getByRole('button', { name: 'Show comments', exact: true }).click();
  await expect(page.locator('.doc-comment-card')).toContainText('Please verify');
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('folio-files-v1')).find(file => file.name === 'Document tools test'));
  assert.deepEqual(saved.pageSetup, { landscape: true, margin: 'narrow', size: 'legal', header: 'Folio test header', footer: 'Folio test footer', pageNumbers: true });
  await expect(page.locator('.doc-status')).toContainText('All changes saved');
  const pendingDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export', exact: true }).click();
  await page.getByRole('button', { name: 'Word document', exact: false }).click();
  const download = await pendingDownload;
  const zip = await JSZip.loadAsync(await readFile(await download.path()));
  const documentXML = await zip.file('word/document.xml').async('string');
  const commentsXML = await zip.file('word/comments.xml').async('string');
  assert.match(documentXML, /w:orient="landscape"/);
  assert.match(documentXML, /w:br w:type="page"/);
  assert.match(documentXML, /w:fill="ABCDEF"/);
  assert.match(documentXML, /w:commentRangeStart/);
  assert.match(commentsXML, /Please verify this paragraph/);
  await page.pdf({ path: '/tmp/folio-word-print.pdf', preferCSSPageSize: true, printBackground: true });
  const printedText = execFileSync('pdftotext', ['-layout', '/tmp/folio-word-print.pdf', '-'], { encoding: 'utf8' });
  assert.match(printedText, /omega beta omega alphabet Alpha/);
  assert.match(printedText, /second PARAGRAPH/);
  assert.equal((printedText.match(/Folio test header/g) || []).length, 2);
  assert.equal((printedText.match(/Folio test footer/g) || []).length, 2);
  await page.screenshot({ path: '/tmp/folio-word-expanded.png' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '/tmp/folio-word-expanded-mobile.png' });
  await page.getByRole('button', { name: 'Delete comment', exact: true }).click();
  await expect(page.locator('.doc-comment-card')).toHaveCount(0);
  assert.doesNotMatch(await html(), /data-comment-id/);
  expect(errors).toEqual([]);
  console.log('PASS: sub/sup exclusivity, format painter, indent/case, cross-mark find/case/word/replace, anchored comments + resolve/reopen/reading protections, page setup preservation, page break, table merge/split/fill/header, image width/alignment, version history, persistence, native DOCX comments/metadata, PDF body + repeating header/footer/page breaks, no browser errors.');
} finally { await browser.close(); }
