import { chromium, expect } from '@playwright/test';
import fs from 'node:fs';
fs.mkdirSync('/tmp/folio-slides-check', { recursive: true });
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000},hasTouch:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{if(sessionStorage.getItem('slides-seeded'))return;sessionStorage.setItem('slides-seeded','1');const t=Date.now();localStorage.setItem('folio-files-v1',JSON.stringify([{id:'slides-test',name:'Slides validation',kind:'presentation',updatedAt:t,createdAt:t,starred:false,trashed:false,content:[{id:'s1',title:'Our product roadmap',body:'A clear direction for the year ahead.',background:'#ffffff',layout:'content'},{id:'s2',title:'Hidden appendix',body:'Private backup slide',background:'#244e40',layout:'content',hidden:true},{id:'s3',title:'The next chapter',body:'Thank you.',background:'#ece7f5',layout:'title',notes:'End with questions.',transition:'fade'}]}]));});
 await page.goto('http://localhost:5173');await page.getByText('Slides validation',{exact:true}).click();await page.getByLabel('Slide title',{exact:true}).waitFor();
 console.log('opened editor');
 await page.getByLabel('Slide title',{exact:true}).fill('Our updated product roadmap');
 await page.getByLabel('Speaker notes',{exact:true}).fill('Discuss the three priorities.\nLeave five minutes for questions.');
 await page.getByLabel('Slide transition',{exact:true}).selectOption('slide');
 await page.getByRole('button',{name:'Text box',exact:true}).click();
 await page.getByLabel('Text box content',{exact:true}).fill('Revenue +32%');
 await page.getByLabel('Object font size',{exact:true}).fill('28');
 await page.getByRole('button',{name:'Bold object text',exact:true}).click();
 await page.getByRole('button',{name:'Align object center',exact:true}).click();
 await page.getByLabel('Object rotation',{exact:true}).fill('5');
 const move=page.getByRole('button',{name:'Move selected object',exact:true});const b=await move.boundingBox();
 await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+75,b.y+36,{steps:10});await page.mouse.up();
 console.log('text box passed');
 await page.getByRole('button',{name:'Rectangle',exact:true}).click();
 await page.getByLabel('Object x',{exact:true}).fill('65');await page.getByLabel('Object y',{exact:true}).fill('40');
 await page.getByLabel('Object width',{exact:true}).fill('20');
 const resize=page.getByRole('button',{name:'Resize selected object',exact:true});const r=await resize.boundingBox();
 await page.mouse.move(r.x+5,r.y+5);await page.mouse.down();await page.mouse.move(r.x+30,r.y+25,{steps:8});await page.mouse.up();
 await page.getByRole('button',{name:'Duplicate selected object',exact:true}).click();
 await page.getByRole('button',{name:'Delete selected object',exact:true}).click();
 await page.getByRole('button',{name:'Undo',exact:true}).click();
 await page.getByRole('button',{name:'Redo',exact:true}).click();
 console.log('shape interactions passed');
 const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==';
 await page.getByLabel('Insert slide picture',{exact:true}).setInputFiles({name:'pixel.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});
 await expect(page.locator('.slides-canvas [data-element-type="image"]')).toHaveCount(1);
 await page.getByRole('button',{name:'Done formatting object',exact:true}).click();
 await page.getByLabel('Slide font family',{exact:true}).selectOption('Georgia');
 await page.getByLabel('Slide title size',{exact:true}).fill('39');
 await page.getByRole('button',{name:'Forest',exact:true}).click();
 await page.waitForTimeout(650);
 const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('folio-files-v1'))[0].content);
 fs.writeFileSync('/tmp/folio-slides-check/before.json',JSON.stringify(before,null,2));
 await page.screenshot({path:'/tmp/folio-slides-check/editor.png',fullPage:true});
 console.log('image inserted');
 await page.getByRole('button',{name:'Present',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Presentation',exact:true})).toContainText('1 / 2');
 await page.getByRole('button',{name:'Show speaker notes',exact:true}).click();
 await expect(page.getByLabel('Presenter notes',{exact:true})).toContainText('Discuss the three priorities.');
 await page.getByRole('button',{name:'Next slide',exact:true}).click();
 await expect(page.getByRole('dialog',{name:'Presentation',exact:true})).toContainText('The next chapter');
 await expect(page.getByRole('dialog',{name:'Presentation',exact:true})).toContainText('2 / 2');
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Export',exact:true}).click();const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'PowerPoint .pptx',exact:true}).click();const download=await downloaded;await download.saveAs('/tmp/folio-slides-check/Slides validation.pptx');
 const imported = await page.evaluate(async encoded => {
   const bytes = Uint8Array.from(atob(encoded), c => c.charCodeAt(0));
   const { importOfficeFile } = await import('/src/lib/fileIO.ts');
   return (await importOfficeFile(new File([bytes], 'Slides validation.pptx', {type:'application/vnd.openxmlformats-officedocument.presentationml.presentation'}))).content;
 }, fs.readFileSync('/tmp/folio-slides-check/Slides validation.pptx').toString('base64'));
 expect(imported).toHaveLength(3);
 expect(imported[0].title).toBe('Our updated product roadmap');
 expect(imported[0].notes).toBe(before[0].notes);
 expect(imported[0].transition).toBe('slide');
 expect(imported[0].fontFamily).toBe('Georgia');
 expect(imported[0].elements).toHaveLength(3);
 expect(imported[0].elements[0]).toMatchObject({type:'text',text:'Revenue +32%',fontSize:28,bold:true,align:'center',rotation:5});
 expect(imported[0].elements[0].x).toBeCloseTo(before[0].elements[0].x, 3);
 expect(imported[0].elements[1]).toMatchObject({type:'shape',shape:'rectangle'});
 expect(imported[0].elements[1].fill.toLowerCase()).toBe('#2d6554');
 expect(imported[0].elements[2].src).toMatch(/^data:image\/png;base64,/);
 expect(imported[1].hidden).toBe(true);
 expect(imported[2].transition).toBe('fade');
 console.log('presentation, export and re-import passed');
 await page.getByRole('button',{name:'Back to workspace',exact:true}).click();await page.getByText('Slides validation',{exact:true}).click();
 await page.reload();await page.getByText('Slides validation',{exact:true}).click();await expect(page.getByLabel('Speaker notes',{exact:true})).toHaveValue('Discuss the three priorities.\nLeave five minutes for questions.');
 await expect(page.locator('.slides-canvas [data-element-id]')).toHaveCount(3);
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Close design panel',exact:true}).click();await page.screenshot({path:'/tmp/folio-slides-check/mobile.png',fullPage:true});
 const shapeBox = await page.locator('.slides-canvas [data-element-type="shape"]').boundingBox();
 const cdp = await page.context().newCDPSession(page);
 const start={x:shapeBox.x+shapeBox.width*.85,y:shapeBox.y+shapeBox.height*.5};
 await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[start]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:start.x+10,y:start.y+10}]});
 await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await page.waitForTimeout(500);
 const mobileState = await page.evaluate(()=>JSON.parse(localStorage.getItem('folio-files-v1'))[0].content);
 expect(mobileState[0].elements[1].x).toBeGreaterThan(before[0].elements[1].x);
 expect(mobileState[0].elements[1].y).toBeGreaterThan(before[0].elements[1].y);
 expect(errors).toEqual([]);
 console.log('PASS: slides editing, drag/resize, object styles, undo/redo, native PPTX export/import, hidden slides, notes, persistence, mobile touch drag.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
