import { chromium, expect } from '@playwright/test';
const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.BASE_URL||'http://localhost:5173');
await page.getByRole('button',{name:'More options for Getting started with Folio'}).click();
await page.getByRole('button',{name:'Version history',exact:true}).click();
await page.getByLabel('Save the current version').fill('Original draft');
await page.getByRole('button',{name:'Save version',exact:true}).click();
await expect(page.locator('.version-item')).toHaveCount(1);
await page.getByRole('button',{name:'Close version history'}).click();
await page.locator('.file-name').filter({hasText:'Getting started with Folio'}).click();
await expect(page.locator('.tiptap')).toBeVisible();
await page.locator('.tiptap').fill('An edited draft which should be preserved.');
await page.getByTitle('Back to workspace').click();
await page.getByRole('button',{name:'More options for Getting started with Folio'}).click();
await page.getByRole('button',{name:'Version history',exact:true}).click();
await page.getByRole('button',{name:'Restore version',exact:true}).click();
await page.locator('.file-name').filter({hasText:'Getting started with Folio'}).click();
await expect(page.locator('.tiptap')).toContainText('A little space for big ideas.');
await expect(page.locator('.tiptap')).not.toContainText('An edited draft');
await page.getByTitle('Back to workspace').click();
await page.reload();
await page.getByRole('button',{name:'More options for Getting started with Folio'}).click();
await page.getByRole('button',{name:'Version history',exact:true}).click();
await expect(page.locator('.version-item')).toHaveCount(2);
await expect(page.locator('.version-item').first()).toContainText('An edited draft which should be preserved.');
await page.getByRole('button',{name:'Close version history'}).click();
await page.getByTitle('Workspace settings').click();
const event=page.waitForEvent('download');await page.getByRole('button',{name:'Back up workspace',exact:true}).click();const backup=await event;await backup.saveAs('/tmp/folio-history-backup.folio.json');
await page.getByLabel('Restore workspace backup').setInputFiles('/tmp/folio-history-backup.folio.json');
await expect(page.locator('.file-row')).toHaveCount(10);
await page.getByRole('button',{name:'More options for Getting started with Folio (restored)'}).click();
await page.getByRole('button',{name:'Version history',exact:true}).click();
await expect(page.locator('.version-item')).toHaveCount(2);
await page.screenshot({path:'/tmp/folio-history.png'});
await page.addInitScript(() => {
  window.failWorkspaceReads=true;
  const transaction=IDBDatabase.prototype.transaction;
  IDBDatabase.prototype.transaction=function(...args){if(window.failWorkspaceReads && (args[1]===undefined||args[1]==='readonly'))throw new DOMException('Temporary read failure','UnknownError');return transaction.apply(this,args);};
});
await page.reload();
await expect(page.getByRole('button',{name:'Retry opening workspace'})).toBeVisible();
await expect(page.locator('.file-row')).toHaveCount(0);
await page.evaluate(()=>{window.failWorkspaceReads=false;});
await page.getByRole('button',{name:'Retry opening workspace'}).click();
await expect(page.locator('.file-row')).toHaveCount(10);
expect(errors).toEqual([]);
console.log('PASS: save version, restore with current-draft recovery, reload, download workspace backup, restore copies with history, failed startup read retry preserves existing workspace.');
await browser.close();
