import { useState } from 'react';
import { ArrowDownToLine, Clock3, History, Plus, RotateCcw, Trash2, X } from 'lucide-react';
import type { OfficeFile, FileVersion } from '../types';
import './workspace-tools.css';
interface Props {file:OfficeFile;busy?:boolean;onClose:()=>void;onSave:(name:string)=>void;onRestore:(version:FileVersion)=>void;onDelete:(id:string)=>void;onDownload:(version:FileVersion)=>void;}
function details(file:OfficeFile,content:any){if(file.kind==='document'){const doc=new DOMParser().parseFromString(typeof content==='string'?content:'','text/html');const text=doc.body.textContent||'';return `${text.trim().split(/\s+/).filter(Boolean).length} words · ${text.slice(0,150)}`;}if(file.kind==='presentation')return `${content?.length||0} slides · ${content?.[0]?.title||'Untitled'}`;const sheets=content?.sheets||[{cells:content?.cells||{},name:content?.name||'Sheet 1'}];return `${sheets.length} worksheet${sheets.length===1?'':'s'} · ${sheets.reduce((n:number,s:any)=>n+Object.keys(s.cells||{}).length,0)} filled cells`;}
export default function VersionHistory({file,busy=false,onClose,onSave,onRestore,onDelete,onDownload}:Props){
 const [name,setName]=useState('');const [pendingDelete,setPendingDelete]=useState<string|null>(null);
 const versions=file.versions||[];
 return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal version-modal" role="dialog" aria-modal="true" aria-label="Version history" onMouseDown={e=>e.stopPropagation()}><button className="icon-button modal-close" aria-label="Close version history" onClick={onClose}><X size={20}/></button><div className="modal-heading"><span className="version-heading-icon"><History size={24}/></span><h2>A little room to go back.</h2><p>Saved versions of <strong>{file.name}</strong></p></div><form className="version-save-form" onSubmit={e=>{e.preventDefault();if(busy)return;onSave(name.trim()||`Version ${versions.length+1}`);setName('')}}><label htmlFor="version-name">Save the current version</label><div><input className="text-input" id="version-name" disabled={busy} value={name} onChange={e=>setName(e.target.value)} maxLength={100} placeholder="Give this moment a name…"/><button className="button primary" type="submit" disabled={busy}><Plus size={16}/>{busy?'Saving…':'Save version'}</button></div></form><div className="version-current"><span className="save-dot"/><strong>Current version</strong><span>{details(file,file.content).split(' · ')[0]}</span></div><div className="version-list">{versions.length?versions.map(version=><article key={version.id} className="version-item"><div className="version-item-heading"><Clock3 size={17}/><div><strong>{version.name}</strong><small>{new Date(version.createdAt).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'})}</small></div><button className="icon-button" aria-label={`Delete version ${version.name}`} disabled={busy} onClick={()=>setPendingDelete(pendingDelete===version.id?null:version.id)}><Trash2 size={15}/></button></div><p>{details(file,version.content)}</p>{pendingDelete===version.id?<div className="version-delete-confirm"><span>Remove this saved version?</span><button disabled={busy} onClick={()=>{onDelete(version.id);setPendingDelete(null)}}>Delete</button><button onClick={()=>setPendingDelete(null)}>Keep</button></div>:<div className="version-actions"><button disabled={busy} onClick={()=>onRestore(version)}><RotateCcw size={14}/>Restore version</button><button onClick={()=>onDownload(version)}><ArrowDownToLine size={14}/>Download copy</button></div>}</article>):<div className="version-empty"><History size={28}/><strong>Every idea deserves a second draft.</strong><p>Save a version before a big change. You can restore it here whenever you need it.</p></div>}</div><p className="version-note">Up to 10 versions per file, saved in this browser. Restoring saves your current work as another version first.</p></section></div>;
}
